### ISSUE TITLE
Do more calls for more download data

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/gbif-dataset-metrics#10]
This download function does only one call to the GBIF API, so if dayRange is high and pageLimit low, it might not retrieve all downloads. Would be better is more calls could be triggered.

**Comment by peterdesmet** [comment]
This should be solved. Not sure I'm the best person to implement this async stuff. :smile:

**Comment by niconoe** [comment]
I'll have a look next Monday!

**Comment by peterdesmet** [comment]
Ok. We should try to close code-contributions by Monday evening, so I can attach a package to the submission.

**Comment by niconoe** [comment]
Guys,

I started to work on this, but unfortunately I'm not able to get rid of the problem easily as expected. Causes are: async stuff is always tricky and my JS skills are rusty, I don't know D3 expect from a tutorial, the code need to be refactored. All together, it seems the fastest way would be to re-learn some D3, then recreate the visualization by myself. I estimate the workload to something like 8 hours, so I was thinking maybe it's not the best course of action at this time?

Alternatives could be:

- stay with one request, but increase the limit parameters so we get more results. That's not solving the problem, but with a limit of 4000 for example we still have reasonably responsive page loads, while (for the moment!) working with highly downloaded datasets.

- Maybe @bartaelterman  or someone more familiar with D3 could have a look. It's probably not that complicated if you have the required skills.

Tell me what you prefer!

**Comment by peterdesmet** [comment]
@niconoe, then I would suggest you leave this as it is. @bartaelterman, do you have an idea on how to tackle this? Not such a problem if we submit it as such, most datasets have fewer downloads.

**Comment by bartaelterman** [comment]
I'm looking into it.

**Comment by bartaelterman** [comment]
I've been able to fix it. With a little luck... :-)

If you set the `pageLimit` parameter at [line 80](https://github.com/Datafable/gbif-dataset-metrics/blob/master/extension/js/activity.js#L80) low (10), and you open the [demo page](https://github.com/Datafable/gbif-dataset-metrics/blob/master/index.html) you can see the activity chart loading more data.

I'm pretty pleased with the result myself, but if you have comments, let me know!

**Comment by niconoe** [comment]
Thanks @bartaelterman, that's just brilliant. I was pretty close, but didn't thought about recursion and got overwhelmed. Seems so obvious now :) thx again!

**Comment by bartaelterman** [comment]
Thanks! I was a bit afraid to end up with an infinite loop, but it worked exactly the way I hoped.
