### ISSUE TITLE
Please update stats of http://www.gbif.org/dataset/83598aa6-f762-11e1-a439-00145eb45e9a/stats

### ISSUE THREAD

**Issue by PacoPando** [Datafable/gbif-dataset-metrics#102]

**Comment by bartaelterman** [comment]
@niconoe can you download this dataset and assign this issue to me when ready?

**Comment by niconoe** [comment]
@bartaelterman, here is the report for that dataset:
[report.json.zip](https://github.com/Datafable/gbif-dataset-metrics/files/336991/report.json.zip)

**Comment by bartaelterman** [comment]
Stats updated, but since the dataset was republished today, the message is still visible.
