### ISSUE TITLE
please re-process TNHC Ichthyology GBIF data set

### ISSUE THREAD

**Issue by deanhend** [Datafable/gbif-dataset-metrics#103]
We have added many records and otherwise improved our data (http://www.gbif.org/dataset/6080b6cc-1c24-41ff-ad7f-0ebe7b56f311/stats) since it was last processed.

**Comment by niconoe** [comment]
That's great if our tool encourage republising of improved dataset! We'll update it very soon, that's a two step process. I'm working on data extraction right now, then @bartaelterman will update our data store.

**Comment by niconoe** [comment]
@bartaelterman, can you proceed with the data aggregation?

JSON report: [0001750-160623103540712.zip.json.zip](https://github.com/Datafable/gbif-dataset-metrics/files/343095/0001750-160623103540712.zip.json.zip)

**Comment by bartaelterman** [comment]
done!

**Comment by deanhend** [comment]
Thanks for the quick update. That's a great tool and certainly helps us
visualize progress and catch glitches. Thanks a bunch for making it
available.

We have a separate data aggregation project (www.fishesoftexas.org) with a
new version of the data and website pretty well along. Providing on-the-fly
summaries like this is high on our list for the next version and I've
pointed our coders to this tool as an example.

Keep up the good work!

Dean
- http://www.fishesoftexas.orgfishesoftexas.org
  http://fishesoftexas.org*

_Dean A. Hendrickson, Curator of Ichthyology_University of Texas Austin
http://www.utexas.edu, Department of Integrative Biology
http://integrativebio.utexas.edu/, Biodiversity Collections
http://integrativebio.utexas.edu/about/collections (Texas Natural History
Collections), 10100 Burnet Rd., PRC176 EAST/R4000, Austin, Texas 78758-4445
USA.
1-512-471-9774, deanhend@austin.utexas.edu

lab website:https://sites.cns.utexas.edu/hendricksonlab
