### ISSUE TITLE
Request for metrics

### ISSUE THREAD

**Issue by kcopas** [Datafable/gbif-dataset-metrics#104]
Hey, gents—any chance you could run a report on this new-ish dataset?
http://www.gbif.org/dataset/83ae84cf-88e4-4b5c-80b2-271a15a3e0fc

all best, from Fiji, fer crying out loud...
KC

**Comment by niconoe** [comment]
@bartaelterman, could you run the aggregator on: [
0005958-160623103540712.zip.json.zip](https://github.com/Datafable/gbif-dataset-metrics/files/365874/0005958-160623103540712.zip.json.zip)

thanks!

**Comment by bartaelterman** [comment]
There you go. This dataset wins two badges!
