### ISSUE TITLE
improve taxonomic overview

### ISSUE THREAD

**Issue by DimEvil** [Datafable/gbif-dataset-metrics#105]
an option for downloading full resolution taxonomic overview .png can be a real nice feature. Especially as this can be used in like data papers. In the added image, not all taxonomic groups are visible.

![image](https://cloud.githubusercontent.com/assets/3965195/17397375/09e4f34e-5a38-11e6-997c-5ec01845cfdd.png)

**Comment by peterdesmet** [comment]
Being able to generate this as static figures for papers would be nice indeed. Maybe it can be done from the SVG, but you would be able to tweak the layout much. It's probably easier to do this with a charting library in R or Python, using the same JSON data. Now you only need to find someone to help you with this. 😄  

You get the taxonomy for a dataset by running this query:

```
http://datafable.cartodb.com/api/v2/sql?q=SELECT+taxonomy+FROM+gbif_dataset_metrics+WHERE+dataset_key+='your_key_of_interest'
```

For example: http://datafable.cartodb.com/api/v2/sql?q=SELECT+taxonomy+FROM+gbif_dataset_metrics+WHERE+dataset_key+=%2750c9509d-22c7-4a22-a47d-8c48425ef4a7%27
