### ISSUE TITLE
Request for metrics

### ISSUE THREAD

**Issue by rdmpage** [Datafable/gbif-dataset-metrics#106]
Hi, I'm working on a DNA barcoding dataset and would be interested in seeing the metrics, the dataset is http://www.gbif.org/dataset/040c5662-da76-4782-a48e-cdea1892d14c

**Comment by bartaelterman** [comment]
Thanks for reaching out @rdmpage!

Since @niconoe is currently unavailable, we'll need a bit more time to crunch the metrics. We'll keep you posted on this issue.

**Comment by niconoe** [comment]
Hey guys, I found a bit of time to extract it: [0006957-160803222355964 (1).zip.json.zip](https://github.com/Datafable/gbif-dataset-metrics/files/429773/0006957-160803222355964.1.zip.json.zip)

cheers from Kigali - BID Workshop

**Comment by bartaelterman** [comment]
Metrics added.

**Comment by rdmpage** [comment]
Thanks very much!
