### ISSUE TITLE
Populate downloaded_at date

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/gbif-dataset-metrics#71]
The aggregation module should have some notion when a dataset was last downloaded for extraction, and populate the field `downloaded_at` in the metrics store. That date is used to display a message if the dataset was republished to GBIF *after* we calculated metrics (which might then be out of date).

Currently, I manually set the `downloaded_at` date to `2015-02-02` for all datasets with metrics.

**Comment by niconoe** [comment]
Done, the key in report is ```ARCHIVE_GENERATED_AT``` and is a simple string such as ```YYYY-MM-DD```.
