### ISSUE TITLE
Datasets with 0 occurrences will never get metrics

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/gbif-dataset-metrics#75]
Some datasets - annoyingly - have [0 occurrences](http://www.gbif.org/dataset/7ac07a58-f762-11e1-a439-00145eb45e9a). As no records from these datasets will end up in the download, we will never have metrics for those and thus never reach 100% of all datasets.

Any suggestions how to tackle those?

**Comment by peterdesmet** [comment]
@bartaelterman is this something we should worry about?

**Comment by bartaelterman** [comment]
I don't think so. The only place where we indicate the number of datasets that we have processed is in the documentation, right?

**Comment by peterdesmet** [comment]
Will just have to exclude those to calculate our 100%.
