### ISSUE TITLE
Something's off with coordinates with major issues

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/gbif-dataset-metrics#76]
Some datasets - where I didn't expect it - are having many occurrences with major issues, for example http://www.gbif.org/dataset/8971dfba-f762-11e1-a439-00145eb45e9a:

* Map looks fine
* Our metrics indicate 299,667 occurrences with major coordinate issues
* However, if I search for occurrences with the 4 issues that are categorized as major, [I only find 890](http://www.gbif.org/occurrence/search?DATASET_KEY=8971dfba-f762-11e1-a439-00145eb45e9a&ISSUE=COORDINATE_OUT_OF_RANGE&ISSUE=ZERO_COORDINATE&ISSUE=COORDINATE_INVALID&ISSUE=COUNTRY_COORDINATE_MISMATCH).

Do we have a bug in our extraction code?

**Comment by bartaelterman** [comment]
Nope, it's an aggregator bug. The report from the extractor indeed contains 890 occurrences with major issues, and 299,667 occurrences with minor issues. Must have mixed them somewhere. Looking into it.
