### ISSUE TITLE
I want metrics for http://www.gbif.org/dataset/5a88d862-075a-4bcd-a726-c4f9cf58cf5f

### ISSUE THREAD

**Issue by DimEvil** [Datafable/gbif-dataset-metrics#77]
http://www.gbif.org/dataset/5a88d862-075a-4bcd-a726-c4f9cf58cf5f

thnx
D

**Comment by peterdesmet** [comment]
@DimEvil, thanks for your report :)
@niconoe, is this included in new download?
@bartaelterman, this would be one for the UPSERT

**Comment by niconoe** [comment]
@peterdesmet @DimEvil Hmmmm, unfortunately the next data batch (soon online) was covering all GBIF as of March 4th, so this is one of the rare datasets that won't be included...

We'll plan a new data update soon, but it takes a couple of days of data extraction (+ a couple of hours of manual work at this stage => to be automated).

**Comment by bartaelterman** [comment]
Since it's requested so politely, we could do a download containing only this dataset since waiting for the next full download will indeed take some time.

**Comment by peterdesmet** [comment]
Yes, @DimEvil did say `thnx`

**Comment by niconoe** [comment]
:+1: Indeed :) Download is being generated at GBIF, will send you the report soon !

**Comment by niconoe** [comment]
Extraction done, report sent to @bartaelterman. It'll be included at next aggregation !

**Comment by bartaelterman** [comment]
Done. I took the liberty to push it to the production table immediately. The rest of the aggregation is still running (on test).

**Comment by niconoe** [comment]
Isn't there a date issue ? I get "Dataset metrics extension: This dataset has been republished since we last crunched the metrics.", but I have ```"ARCHIVE_GENERATED_AT": "2015-03-09"``` in the report.

**Comment by bartaelterman** [comment]
Yes. However, I have the impression that this is an issue in the plugin. The date in the CartoDB table is the same as in the report.

See the result of this [API call](http://datafable.cartodb.com/api/v2/sql?q=SELECT%20archive_generated_at,dataset_key%20FROM%20public.gbif_dataset_metrics%20where%20dataset_key=%275a88d862-075a-4bcd-a726-c4f9cf58cf5f%27)

**Comment by bartaelterman** [comment]
From the corresponding IPT site, it looks like there has been a republication of this dataset today. However, we only provide the date, which translates to a date time event with time 00:00:00. So if this dataset was indeed replublished today, then that timestamp will be later than our `archive_generated_at`.

Only solution would be to include the time in the `ARCHIVE_GENERATED_AT` of the extractor report.

**Comment by peterdesmet** [comment]
@bartaelterman, I'll let you check that we have metrics for this dataset after the whole run is finished.

**Comment by bartaelterman** [comment]
The dataset key is included in the extracted data. I will close this issue when the aggregation run finished.

**Comment by peterdesmet** [comment]
@DimEvil, at long last, there are metrics for your dataset: http://www.gbif.org/dataset/5a88d862-075a-4bcd-a726-c4f9cf58cf5f/stats
