### ISSUE TITLE
Update metrics for all datasets

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/gbif-dataset-metrics#78]
This is the status so far:

type | occ_api | occ | updated | newly_created | count | remarks
--- | --- | --- | --- | --- | --- | ---
OCCURRENCE | false | true | true | true | 49 | OK, new datasets
OCCURRENCE | true | false | false | false | 672 | Still to update
OCCURRENCE | false | false | false | false | 379 | OK, no real need to update this
OCCURRENCE | true | true | false | false | 1790 | Were once updated, should be done again
OCCURRENCE | false | true | true | false | 19 | Since when did these datasets get occ?
OCCURRENCE | false | true | false | false | 1 | Added last time, should be updated
OCCURRENCE | true | true | true | false | 9472 | OK, updated datasets
METADATA | true | true | true | false | 3 | OK, odd to such datasets with occ though
METADATA | false | false | false | false | 21 | OK, no real need to update this
METADATA | true | false | false | false | 1 | OK, no real need to update this
METADATA | true | true | false | false | 1 | OK, apparently updated last time
CHECKLIST | false | true | true | false | 122 | Since when did these datasets get occ?
CHECKLIST | true | true | true | false | 479 | OK, recently updated
CHECKLIST | true | true | false | false | 183 | OK, no real need to update this
CHECKLIST | false | true | false | false | 9 | OK, apparently these datasets got occ last time
CHECKLIST | false | false | false | false | 750 | OK, no real need to update this
CHECKLIST | true | false | false | false | 48 | OK, no real need to update this

SQL used:

```SQL
SELECT
	type,
	CASE
		WHEN occurrences_api > 0 THEN True
		ELSE False
	END AS occ_api,
	CASE
		WHEN occurrences > 0 THEN True
		ELSE False
	END AS occ,
	CASE
		WHEN updated_at >= '2015-03-12' THEN True
		ELSE False
	END AS updated,
	CASE
		WHEN created_at >= '2015-03-12' THEN True
		ELSE False
	END AS newly_created,
	count(*)
FROM gbif_dataset_metrics_test
GROUP BY
	type,
	occ_api,
	occ,
	updated,
	newly_created
ORDER BY
	type DESC
```

**Comment by peterdesmet** [comment]
@bartaelterman, I think our best way forward is to focus on `OCCURRENCE` datasets. Could you add a filter to the aggregator to only aggregate and push those datasets? I think I'll also create a new base table, with a complete new set of all datasets at GBIF.

**Comment by peterdesmet** [comment]
Here are the updated numbers from GBIF on what we should get:

type | occ_api | count | remarks
--- | --- | --- | ---
OCCURRENCE | true | 12034 | This is the number we need to hit
OCCURRENCE | false | 363 | Ignore, no occurrences
METADATA | true | 4 | Ignore, wrong type
METADATA | false | 23 | Ignore, wrong type
CHECKLIST | true | 870 | Ignore, wrong type
CHECKLIST | false | 754 | Ignore, wrong type

SQL:

```SQL
SELECT
	type,
	CASE
		WHEN occurrences_api > 0 THEN True
		ELSE FALSE
	END occ_api,
	count(*)
FROM gbif_dataset_metrics_test2
GROUP BY
	type,
	occ_api
```

**Comment by peterdesmet** [comment]
@niconoe, can you do a new extract of all GBIF data as soon as possible and pass the resulting data to @bartaelterman ?

**Comment by peterdesmet** [comment]
@niconoe, when did you download the data? How many datasets are in the extract? How many occurrences? I need this information for the readme.

**Comment by niconoe** [comment]
Hi @peterdesmet, the data has been downloaded on August 5th and covers 577 245 398 records - 13 187 datasets.

**Comment by peterdesmet** [comment]
Do you know how many OCCURRENCE datasets?

**Comment by peterdesmet** [comment]
Also, since then, number of occurrences has dropped to 570 million?

**Comment by niconoe** [comment]
The data came from the "my downloads" page at GBIF, so I don't know if these numbers are correct or no. Indeed, it's weird that the number of datasets seems to be for everything, while the download itself was only targeting occurrences data.

So there may be a bug in the portal. Do you know how we got those numbers last time? Maybe they are esay to extract at aggregation run? Maybe @bartaelterman has an opinion on this?

**Comment by peterdesmet** [comment]
@niconoe, I've updated download date, occurrences and number of occurrence datasets in the readme with the information I currently see at GBIF: a58d1918858b22006f184bd09c876e2f80961952.

**Comment by niconoe** [comment]
I had to re-download the August 5th export, since the poral failed to create a new full export for me this morning, and given the very short deadline, I decided to take the previous version...

**Comment by peterdesmet** [comment]
Ouch, too bad... you should maybe ask Tim?

**Comment by peterdesmet** [comment]
@niconoe, I would really try again! I'll download as well.

**Comment by niconoe** [comment]
Ok, I try again right now (these errors are common, and generally don't last). This will however add around 1 day of additional delay (generating + downloading + splitting archive). I (yesterday) thought we didn't had this time.

**Comment by niconoe** [comment]
So, if this download is the final one, the metrics will be:

13.323 occurrence datasets - september 1st - 570.238.233 occurrences.

**Comment by peterdesmet** [comment]
My download has finished (I'll send you the link). I used the information from the GBIF frontpage for the numbers and had 13,**23**3 occurrences datasets, covering the same 570,238,233 occurrences. The download itself mentions 570,238,**726** records, 13.2**20** though. I think that is close enough. :-)

**Comment by niconoe** [comment]
File detected as invalid in the middle of the decompression process. Don't know if the corruption happened during decompression, download or generation. I'll try again to unzip the downloaded file, if it fails I'll download my search from this morning. This is a bit stressful, each of those small glitches takes at least half a day...

**Comment by niconoe** [comment]
Peter suggested asking Tim Robertson if he has a full file that works for sure. That may be an option, but I first try with the last version I generated this morning since 1) It's already started 2) Tim probably doesn't have very recent files 3) it's quite possible the corruption happened at download or due to a bug in my unzip command, so the problem could be just the same.

**Comment by niconoe** [comment]
Other suggestion of trying to unzip on your computer: yeah, why not. The link to my version is http://www.gbif.org/occurrence/download/0000313-150831095807960, yours would be perfect too if that works.

To do this you'll need an unzip tool that support large files (ZIP64). Around 600Gb on free space, on a removable drive that you can pass me later. You don't need to extract verbatim.txt, but all the other files are necessary.

Given the time everything takes (just transfer for example), it has a high chance of being unnecessary (if I succeed before you). But doing in in parallel maybe useful, just in case. I keep you in touch of the progress!

**Comment by bartaelterman** [comment]
I don't have 600GB of free space on a removable drive, so I'm afraid I can't help with this. We could also fire up another EC2 instance?

**Comment by niconoe** [comment]
That maybe a solution, but I think you also pay a fee for the transfer, no? Because in that case, we have 90+ Gb to load on the machine.

That will probably work after a few tries just like we do now (that always did!), but we're a bit playing with fire here between: stupid errors on my side last week, last-minute work, decision to load a brand new file instead of an older that's known to be correct, ... The extraction itself is working well and quite optimized, but all the small things gets complicated when you're working with such a data volume.

**Comment by peterdesmet** [comment]
@niconoe, if you're still stuck this evening, I'll try and see if I can unpack the file at home (I don't have the space on my laptop).

**Comment by bartaelterman** [comment]
Yes, I totally agree. And indeed, you also pay for the data transfer. So let's just keep trying. A new version of the extension can already be released, so if a dataset contained multimedia as `stillimages` they will be shown correctly.

**Comment by niconoe** [comment]
Very good, thanks.

**Comment by peterdesmet** [comment]
I published the final extension (v2.0.1) yesterday. For the submission, I only need the sample of images documentation (#59), which I'm also waiting for to publish to GitHub pages (although not really required). For the metrics data, we have time till Saturday to get this in production

**Comment by peterdesmet** [comment]
Hi @niconoe, are the numbers in the README ok now: https://github.com/Datafable/gbif-dataset-metrics#limitations ?

**Comment by niconoe** [comment]
Nope :)

September 1st - 570 238 726 records - 13221 occurrence datasets (that one is surprising hard to get reliably, let's say that's close enough)

**Comment by peterdesmet** [comment]
Updated in a0ac2863cbb979362a4c02c0c3b49cd0e5e61618
