### ISSUE TITLE
Answer to comments jury

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/gbif-dataset-metrics#80]

**Comment by peterdesmet** [comment]
Done in Google Doc: can you guys review?

**Comment by bartaelterman** [comment]
Done. Nico and I will see on what infrastructure we run the aggregation and update the document accordingly.

**Comment by peterdesmet** [comment]
Thanks!

**Comment by niconoe** [comment]
I let a small comment/question about the last paragraph, but I'm otherwise pleased with the answers!

**Comment by peterdesmet** [comment]
I answered it. Once OK, I'll copy the feedback to this repo at https://github.com/Datafable/gbif-dataset-metrics/blob/master/documentation/feedback-to-comments.md, which I'm already referencing in the README.

**Comment by peterdesmet** [comment]
Last section updated (in repo) to:

> Another case in point that this processing should be done more efficiently, tied more closely to GBIF's harvesting and indexing infrastructure, and on a larger infrastructure overall, is that we were not able to process all of GBIF’s data on our development infrastructure (i.e. a MacBook Pro), but had to rely on [Amazon EC2 infrastructure](https://aws.amazon.com/ec2/) to aggregate all metrics from the occurrences in a reasonable time span. Even then, downloading takes 0.5 days, extracting metrics 2 days, and aggregating (on EC2) a couple of hours.

Good?

**Comment by peterdesmet** [comment]
I also extended the section on why we need to do this on the GBIF infrastructure. https://github.com/Datafable/gbif-dataset-metrics/blob/master/documentation/feedback-to-comments.md
