### ISSUE TITLE
Update description and republish extension

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/gbif-dataset-metrics#81]
## Structure

* [x] Copy `Rationale` from README as 1st paragraph
* [x] Copy `Result` from README as 2nd paragraph
* [x] Copy `Result` from README as 3rd paragraph
* [x] Provide easy installation instructions

> You can use the extension by [installing it from the Chrome web store](https://chrome.google.com/webstore/detail/gbif-dataset-metrics/kcianglkepodpjdiebgidhdghoaeefba) and going to a [GBIF dataset page](http://www.gbif.org/dataset/0debafd0-6c8a-11de-8225-b8a03c50a862). Don't want to install the extension, but just see a preview? [See this demo page](http://datafable.com/gbif-dataset-metrics/). Source code and documentation are available in [this repository](https://github.com/datafable/gbif-dataset-metrics), which is also attached as a zip file.

## Mention

* [x] Multimedia sample
* [x] Aggregated all datasets this time
* [x] Link to feedback to jury
* [x] Remove note at the top

## Update at

* [x] At challenge website
* [x] At GitHub
* [x] At Chrome Web Store

**Comment by peterdesmet** [comment]
Updated parts of the README on GitHub. Will be copied to other to websites.

**Comment by peterdesmet** [comment]
In v1 we provided a website with functionality of extension for a single dataset: http://datafable.com/gbif-dataset-metrics/ Do we do this again, or assume everyone will be using the extension?

**Comment by niconoe** [comment]
IMHO, it would be nice to have but not absolutely necessary. Is it a big effort to do it?

**Comment by peterdesmet** [comment]
We'll see. I've updated the README with all the work we plan to do for round 2. I consider README finished except for number of OCCURRENCE datasets included in download

**Comment by peterdesmet** [comment]
Updated everywhere, assuming we have data from today.
