### ISSUE TITLE
Investigate bookmarklet

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/gbif-dataset-metrics#82]
Questions:

1. Can the bookmarklet run automatically or does the user need to click? If the latter, it's not worth to implement this.
2. Can we host the code publicly elsewhere (is already on gh-pages), so not all code is included in bookmarklet.

**Comment by bartaelterman** [comment]
1. According to [this link](http://stackoverflow.com/questions/7417778/how-can-a-bookmarklet-automatically-run-without-interaction-is-that-a-security) a bookmarklet cannot run without user interaction.  The [wikipedia page](https://en.wikipedia.org/wiki/Bookmarklet) suggests the same thing.
