### ISSUE TITLE
Sample of images: url

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/gbif-dataset-metrics#86]
For [this dataset](http://www.gbif.org/dataset/65339e28-add7-11e2-8fbc-00145eb45e9a), I currently get this in `images_sample` (data from March):

```
{
"784636238": "http://www.globis.insects-online.de/?q=node/3&s=1110",
"784635741": "http://www.globis.insects-online.de/?q=node/3&s=9330",
"893488832": "http://www.globis.insects-online.de/?q=node/3&s=8884",
...
```

Those URLs are not images however. On the occurrence page, e.g. http://www.gbif.org/occurrence/784636238, you can see there are 6 images linked to that occurrence, and the URL mentioned above is the image home, not the actual url of the image file.

@niconoe, @bartaelterman:

* Is it possible populate with the URL with the link to the actual image file. That info should be there somewhere in multimedia extension, as GBIF can show it correctly.
* Is the fact that there are more images for one occurrences messing things up?

**Comment by peterdesmet** [comment]
Also a problem for http://www.gbif.org/dataset/7377c214-e7f1-4fc0-a9de-3b85728ccc11

**Comment by peterdesmet** [comment]
I guess this is an extractor issue? If so, it should be solved soon, otherwise we cannot implement the sample of images feature.

**Comment by bartaelterman** [comment]
Indeed, the links in the extracted data look exactly like that.

**Comment by peterdesmet** [comment]
@niconoe, the error in the extractor is here: https://github.com/Datafable/gbif-dataset-metrics/blob/992510b0920c0607e0f49370ad07fdbc8558e182/extraction_module/bin/extract_data.py#L66

Instead of `http://purl.org/dc/terms/references`, we need `DCTERMS:IDENTIFIER`. See http://rs.gbif.org/extension/gbif/1.0/multimedia.xml

Can you rerun the extractor? Is it possible to only do so for datasets with multimedia?

**Comment by peterdesmet** [comment]
Discussed with @niconoe: he'll correct the bug today and to a test extract run. We can then verify if we get back the correct data, after which a full extract run will be done. This will take 2 days. We decided not to redownload data (currently from August 5) as that would add another day.

**Comment by bartaelterman** [comment]
Doing so only for datasets only with multimedia could become difficult in the aggregation. At least I will have to run it twice. (once on the currently extracted data, and a second run to only update the datasets with media).

On the other hand, the aggregation is much faster then the extraction now, so it might be best to optimize the extractor. I can provide a list with dataset keys of datasets that have multimedia. Can the extractor work with this @niconoe ?

**Comment by peterdesmet** [comment]
@niconoe said that the most fail-proof way is to extract all again.

**Comment by niconoe** [comment]
Extraction in progress, I'll send a first report as soon as it's ready so we can inspect it and check everything seems good ASAP!

**Comment by peterdesmet** [comment]
Seems good in test run, I'll close this issue.
