### ISSUE TITLE
http://www.gbif.org/dataset/3c428404-893c-44da-bb4a-6c19d8fb676a/stats

### ISSUE THREAD

**Issue by DimEvil** [Datafable/gbif-dataset-metrics#94]
stats please :)

**Comment by peterdesmet** [comment]
http://www.gbif.org/dataset/3c428404-893c-44da-bb4a-6c19d8fb676a/stats

**Comment by niconoe** [comment]
Extraction done and report sent to @bartaelterman !

**Comment by bartaelterman** [comment]
done, but the dataset was republished today so the message about the outdated stats is still visible.
