### ISSUE TITLE
Update metrics request: INBO Bird tracking dataset

### ISSUE THREAD

**Issue by kcopas** [Datafable/gbif-dataset-metrics#96]
Many thanks!

**Comment by peterdesmet** [comment]
Thanks for the request Kyle. Can't get enough of the bird tracking data? :-)

@niconoe @bartaelterman, can you reprocess http://www.gbif.org/dataset/83e20573-f7dd-4852-9159-21566e1e691e ? And if possible/if you have time, maybe reanalyze all datasets that have been republished? I don't know if one can query for that though...

**Comment by kcopas** [comment]
You know it -->

Was hoping to get a good screenshot to use to represent the Ebbe. Thought
it might be a doubly apt example.

Thanks for the request Kyle. Can't get enough of the bird tracking data? :-)



=====
*Kyle Copas*
Weysesgade 43
2100 Copenhagen Ø
(+45) 28 75 14 75 | skype kylecopas

**Comment by bartaelterman** [comment]
Updated.

**Comment by peterdesmet** [comment]
Those are some [boring metrics](http://www.gbif.org/dataset/83e20573-f7dd-4852-9159-21566e1e691e/stats) though: everything is perfect. :smile:

**Comment by kcopas** [comment]
True. Should've known that. Wishing for a good dope-slap emoji about now...

=====
*Kyle Copas*
Weysesgade 43
2100 Copenhagen Ø
(+45) 28 75 14 75 | skype kylecopas

**Comment by niconoe** [comment]
Yeah, I also thought there was a bug in the process when I saw the report file was so tiny. After spending a good 5 minutes looking around, I had to conclude it was just clean data :)

**Comment by peterdesmet** [comment]
Of course it's clean data. It's LifeWatch INBO data. :-)
