### ISSUE TITLE
updating of metrics

### ISSUE THREAD

**Issue by wcoetzer** [Datafable/gbif-dataset-metrics#97]
Please will you update the metrics of this dataset: http://www.gbif.org/dataset/1aaec653-c71c-4695-9b6e-0e26214dd817/stats

**Comment by niconoe** [comment]
Sure, I'll extract the data really soon then ask help to my colleague @bartaelterman to store the new metrics in our backend! We'll let you know.

**Comment by bartaelterman** [comment]
@niconoe can you extract this one again? The dataset was republished yesterday, so the header indicated the metrics are out of date is still there.

**Comment by niconoe** [comment]
Sorry, I missed the notification. Extraction done and transmitted again!

**Comment by bartaelterman** [comment]
Done
