### ISSUE TITLE
Dataset metrics, please

### ISSUE THREAD

**Issue by kcopas** [Datafable/gbif-dataset-metrics#98]
Newish dataset: would you, could you crunch some numbers?

Thx!

**Comment by bartaelterman** [comment]
Hi Kyle, we're not systematically updating all datasets. Could you leave the dataset id for which you would like to see the statistics?

**Comment by kcopas** [comment]
Apologies—didn't consider that the dataset in question wouldn't come
through in the request!
dataset key: 5a12d9c3-9465-4107-bb39-2cb451e6cef6
a.k.a. doi:10.15468/wwds1e


=====
*Kyle Copas*
Weysesgade 43
2100 Copenhagen Ø
(+45) 28 75 14 75 | skype kylecopas

**Comment by niconoe** [comment]
@kcopas Sorry for the delay, your message was unnoticed.

@bartaelterman: it is now extracted, here is the report: https://www.dropbox.com/s/064zllp04xohjrn/0013895-160311141623029.zip.json?dl=0. Can you aggregate it?

@kcopas: once done, the metric will finally be visible.

**Comment by bartaelterman** [comment]
@kcopas there you go!

**Comment by kcopas** [comment]
Thanks, guys!

Let me take the opportunity to say (on my personal email account) that we
really have to figure out how to work with you to either expand the
platforms it will work on or integrate this tool within GBIF.org. It really
is fantastic.

Look forward to hearing from you on official channels.

KC

=====
*Kyle Copas*
Weysesgade 43
2100 Copenhagen Ø
(+45) 28 75 14 75 | skype kylecopas

**Comment by bartaelterman** [comment]
Thanks @kcopas, that's great to hear!

**Comment by peterdesmet** [comment]
Thanks @kcopas, I'm using our tool often too. 😄
